version: '3.9'
services:
  app-chat:
    build: .
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/chat-app
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: chitchat-cloudflared
    restart: always
    command: tunnel run
    env_file:
      - .env
    depends_on:
      - app-chat

volumes:
  mongo-data:
